import Layout from "@/components/layout/Layout"
import Blog4 from "@/components/sections/Blog4"
import Category from "@/components/sections/Category"
import DealProduct1 from "@/components/sections/DealProduct1"
import DealProduct3 from "@/components/sections/DealProduct3"
import Pricing from "@/components/sections/Pricing"
import Product1 from "@/components/sections/Product1"
import Shop from "@/components/sections/Shop"
import Slider1 from "@/components/sections/Slider1"
import Team from "@/components/sections/Team"
import Testimonial2 from "@/components/sections/Testimonial2"
export const metadata = {
    title: 'Ninico - Minimal NextJS React Template',
    description: 'Generated by create next app',
}
export default function Home() {
    return (
        <>
            <Layout headerStyle={1} footerStyle={1}>
                <Slider1 />
                <Category />
                <Product1 />
                <DealProduct3/>
                <Pricing/>
                {/* <Shop /> */}
                <Team/>
                <Testimonial2/>
                <DealProduct1 />
                <Blog4/>
            </Layout>
        </>
    )
}